patients: 18994
activation_ntest: 1                                   #0 for off, 1 for column-wise counting, 2 for global counting
activation_gradient: 2
predicting_method: 'sigmoid'
 processing_method: 'deterministic'
state_quick_calc: True
activation_NN_1: False
activation_NN_2: False
activation_NN_3: False
