patients: 500
activation_ntest: 1                                   #0 for off, 1 for column-wise counting, 2 for global counting
activation_gradient: 1
predicting_method: 'sigmoid'
 processing_method: 'deterministic'
selection_method: 'selective'
magicfactor_testnumber: 0.8
magicfactor_vitalgradient: 0.1
