patients: 600
activation_ntest: 1                                   #0 for off, 1 for column-wise counting, 2 for global counting
activation_gradient: 0
predicting_method: 'probability'
 processing_method: 'deterministic'
state_quick_calc: False
activation_NN_1: True
activation_NN_2: False
